"""init"""

revision = '72070fbb0218'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('student_no', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('class_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_class_type'), 'students', ['class_type'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_phone'), 'students', ['phone'], unique=True)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_index(op.f('ix_students_student_no'), 'students', ['student_no'], unique=True)
    op.create_table('lesson_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_lesson_records_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_records'))
    )
    op.create_index(op.f('ix_lesson_records_change_type'), 'lesson_records', ['change_type'], unique=False)
    op.create_index(op.f('ix_lesson_records_student_id'), 'lesson_records', ['student_id'], unique=False)
    op.create_index('ix_lesson_records_student_id_created_at', 'lesson_records', ['student_id', 'created_at'], unique=False)
    op.create_index('ix_lesson_records_student_id_subject_name', 'lesson_records', ['student_id', 'subject_name'], unique=False)
    op.create_index(op.f('ix_lesson_records_subject_name'), 'lesson_records', ['subject_name'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_type', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payments_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_pay_type'), 'payments', ['pay_type'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_index('ix_payments_student_id_created_at', 'payments', ['student_id', 'created_at'], unique=False)
    op.create_table('student_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deducted_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_subjects_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_subjects')),
    sa.UniqueConstraint('student_id', 'subject_name', name='uq_student_subjects_student_subject')
    )
    op.create_index(op.f('ix_student_subjects_student_id'), 'student_subjects', ['student_id'], unique=False)
    op.create_index('ix_student_subjects_student_id_subject_name', 'student_subjects', ['student_id', 'subject_name'], unique=False)
    op.create_index(op.f('ix_student_subjects_subject_name'), 'student_subjects', ['subject_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_subjects_subject_name'), table_name='student_subjects')
    op.drop_index('ix_student_subjects_student_id_subject_name', table_name='student_subjects')
    op.drop_index(op.f('ix_student_subjects_student_id'), table_name='student_subjects')
    op.drop_table('student_subjects')
    op.drop_index('ix_payments_student_id_created_at', table_name='payments')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_pay_type'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lesson_records_subject_name'), table_name='lesson_records')
    op.drop_index('ix_lesson_records_student_id_subject_name', table_name='lesson_records')
    op.drop_index('ix_lesson_records_student_id_created_at', table_name='lesson_records')
    op.drop_index(op.f('ix_lesson_records_student_id'), table_name='lesson_records')
    op.drop_index(op.f('ix_lesson_records_change_type'), table_name='lesson_records')
    op.drop_table('lesson_records')
    op.drop_index(op.f('ix_students_student_no'), table_name='students')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_phone'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_class_type'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
